name: Build

on:
  push:
  release:
    types: [released]

jobs:
  athena:
    name: Build for Athena
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build "conduit/wpilibio"
        run: bazel build --config=athena //conduit/wpilibio
      - name: Build "conduit/api"
        run: bazel build //conduit/api
      - name: Build "junction/core"
        run: bazel build //junction/core
      - name: Build "junction/shims/wpilib"
        run: bazel build //junction/shims/wpilib
      - name: Get version number
        id: get_version
        if: github.event_name == 'release'
        uses: battila7/get-version-action@v2
      - name: Upload "conduit/wpilibio"
        if: github.event_name == 'release'
        run: bazel run --config=athena --define "maven_repo=https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit" --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" --define "publishing_nativezip_generate_pom=true" //conduit/wpilibio:nativezip.publish
        env:
          GITHUB_ACTOR: Mechanical-Advantage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload "conduit/api"
        if: github.event_name == 'release'
        run: bazel run --define "maven_repo=https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit" --define "maven_user=Mechanical-Advantage" --define "maven_password=${{ secrets.GITHUB_TOKEN }}" --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //conduit/api:api-export.publish
      - name: Upload "junction/core"
        if: github.event_name == 'release'
        run: bazel run --define "maven_repo=https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit" --define "maven_user=Mechanical-Advantage" --define "maven_password=${{ secrets.GITHUB_TOKEN }}" --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //junction/core:core-export.publish
      - name: Upload "junction/shims/wpilib"
        if: github.event_name == 'release'
        run: bazel run --define "maven_repo=https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit" --define "maven_user=Mechanical-Advantage" --define "maven_password=${{ secrets.GITHUB_TOKEN }}" --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //junction/shims/wpilib:wpilib-export.publish
     
  desktop:
    strategy:
      matrix:
        host:
          - {os: macos-latest, displayName: "macOS"}
          - {os: ubuntu-latest, displayName: "Linux"}
          - {os: windows-latest, displayName: "Windows"}

    name: Build for ${{ matrix.host.displayName }}
    runs-on: ${{ matrix.host.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build "conduit/wpilibio"
      run: bazel build //conduit/wpilibio
    - name: Build "conduit/api"
      run: bazel build //conduit/api
    - name: Build "junction/core"
      run: bazel build //junction/core
    - name: Build "junction/shims/wpilib"
      run: bazel build //junction/shims/wpilib
    - name: Get version number
      id: get_version
      if: github.event_name == 'release'
      uses: battila7/get-version-action@v2
    - name: Upload "conduit/wpilibio"
      if: github.event_name == 'release'
      run: bazel run --define "maven_repo=https://maven.pkg.github.com/Mechanical-Advantage/AdvantageKit" --define "publishing_version=${{ steps.get_version.outputs.version-without-v }}" //conduit/wpilibio:nativezip.publish
      env:
        GITHUB_ACTOR: Mechanical-Advantage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}